protected/modules/admin/controllers/BankController.php
<?php

class BankController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','merge'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Bank;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Bank']))
		{
			$model->attributes=$_POST['Bank'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Bank']))
		{
			$model->attributes=$_POST['Bank'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Bank');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Bank('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Bank']))
			$model->attributes=$_GET['Bank'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Bank::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='bank-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/modules/admin/controllers/ProductController.php
<?php

class ProductController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view', 'merge'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('populatedData', 'searchQuote', 'getMonthWiseData', 'changeStatus', 'download', 'tariff', 'filter', 'getUtilities'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('create', 'admin', 'delete', 'getCsvHeader', 'startDate', 'quote', 'getParams', 'searchEQuote', 'calculate', 'products', 'productType', 'update', 'csvMapping', 'csvForm', 'csvView'),
                'expression' => 'Yii::app()->user->getIsAdmin()',
            //  'users' => array('admin'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete', 'getCsvHeader', 'quote', 'getParams', 'searchEQuote', 'calculate'),
                'expression' => 'Yii::app()->user->getIsUser()',
            //  'users' => array('admin'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'quote', 'getParams', 'searchEQuote', 'calculate'),
                'expression' => 'Yii::app()->user->getIsSupplier()',
            //  'users' => array('admin'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete', 'getCsvHeader', 'quote', 'getParams', 'searchEQuote', 'calculate'),
                'expression' => 'Yii::app()->user->getIsAgency()',
            //  'users' => array('admin'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete', 'getCsvHeader', 'quote', 'getParams', 'searchEQuote', 'calculate'),
                'expression' => 'Yii::app()->user->getIsCustomer()',
            //  'users' => array('admin'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id) {
        $model = $this->loadModel($id);
        // $price = new Price();
        // $dataProvider = $price->search($id);
        $price = new Price('search', array('id' => $id));
        $price->unsetAttributes();  // clear any default values
        if (isset($_GET['Price']))
            $price->attributes = $_GET['Price'];
        $this->render('view', array(
            'model' => $model,
            //'dataProvider' => $dataProvider,
            'price' => $price
        ));
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionCsvView($id) {


        $model = $this->loadModel($id);
        $file = $model->csv_file;
        $csv = $model->readCsvContents();
        $to_remove = array("0");
        $result = array_diff_key($csv, array_flip($to_remove));
//
        if (isset($_POST['Product'])) {
            $attrs = $_POST['current_attribute'];
            //echo '<pre>'; print_r($attrs); die;
            $attr = serialize($attrs);
            $model->columns_name = $attr;
            $model->csv_file = $file;
            //echo '<pre>'; print_r($result); die;
            $model->save(false);

            /////////////////////////////////////

            $field = Fields::model()->findByAttributes(array(
                'utility' => $model->utility,
                'corporate_sme' => $model->corporate_sme,
                'assigned_to' => $model->assigned_to,
            ));
            if (!$field) {
                $field = new Fields;
                $field->utility = $model->utility;
                $field->corporate_sme = $model->corporate_sme;
                $field->assigned_to = $model->assigned_to;
                // $field->product_id = $model->product_id;
                $field->fields = $model->columns_name;
                $field->save();
            }
            ////////////////////////////////////


            foreach ($result as $k => $attr) {
                $final = array_combine($attrs, $attr);
                $price = new Price;
                $price->setAttributes($final);
                $price->product_id = $model->id;
                if ($price->save()) {
                    Yii::app()->user->setFlash('success', "Price of the product saved successfully..!");
                } else {
                    Yii::app()->user->setFlash('error', "Something went wrong to save csv..!");
                }
            }
            $this->redirect(array('view', 'id' => $model->id));
        }
        $this->render('csvView', array(
            'model' => $model,
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new Product;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);
        $model->scenario = 'create';


        if (isset($_POST['Product'])) {

            $model->attributes = $_POST['Product'];
            $model->created = new CDbExpression('NOW()');
            $model->saveUploadedFile($model, 'csv_file');

            if ($model->save()) {
                ////////////////
                $field = Fields::model()->findByAttributes(array(
                    'utility' => $model->utility,
                    'corporate_sme' => $model->corporate_sme,
                    'assigned_to' => $model->assigned_to,
                ));
                if ($field) {
                    $model->columns_name = $field->fields;
                    $model->save();
                    //  $field->product_id = $model->id;
                    $field->save();
                    Price::saveCsv($field->fields, $model);
                    $this->redirect(array('view', 'id' => $model->id));
                } else {
                    //////////////
                    $this->redirect(array('csvView', 'id' => $model->id));
                }
            }
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);
        if (isset($_POST['Product'])) {
            $file = $model->csv_file;
            $field = Fields::model()->findByAttributes(array(
                'utility' => $model->utility,
                'corporate_sme' => $model->corporate_sme,
                'assigned_to' => $model->assigned_to,
            ));

            if ($field && $field->utility != $_POST['Product']['utility'] || $field->corporate_sme != $_POST['Product']['corporate_sme']) {
                $field->utility = $_POST['Product']['utility'];
                $field->corporate_sme = $_POST['Product']['corporate_sme'];
                $field->save();
            }
            $model->attributes = $_POST['Product'];
            $model->csv_file = $file;
//            echo '<pre>';
//            print_r($model);
//            die;
            if ($model->save(false))
                $this->redirect(array('view', 'id' => $model->id));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        if (Yii::app()->request->isPostRequest) {
            $model = $this->loadModel($id);
//            $model->save();
            // we only allow deletion via POST request
            /////////////////////
            $criteria = new CDbCriteria;
            $criteria->addCondition('product_id=' . $id);
            $prices = Price::model()->findAll($criteria);
            foreach ($prices as $price) {
                ContractDetail::model()->deleteAllByAttributes(array('price_id' => $price->id));
                Quote::model()->deleteAllByAttributes(array('price_id' => $price->id));
            }
            Price::model()->deleteAllByAttributes(array('product_id' => $id));
            /////////////////
            $criteria = new CDbCriteria;
            $criteria->addCondition('utility=' . $model->utility);
            $criteria->addCondition('corporate_sme=' . $model->corporate_sme);
            $criteria->addCondition('assigned_to=' . $model->assigned_to);

protected/modules/admin/views/product/_csvform.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Csv Form</h3>
</div>
<div class="modal-body">

    <?php
    $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
        'id' => 'product-form',
        'action'=>$this->createUrl("product/admin"),
        'enableAjaxValidation' => false,
        'enableClientValidation' => false,
        'clientOptions' => array(
            'validateOnSubmit' => true,
        ),
        'htmlOptions' => array('enctype' => 'multipart/form-data'),
    ));
    ?>


    <p class="help-block">Fields with <span class="required">*</span> are required.</p>

    <?php echo $form->fileFieldRow($model, 'csvfile', array("required" => "required")); ?>

    <?php /* echo $form->errorSummary($model); ?>

      <?php echo $form->textFieldRow($model, 'utility', array('class' => 'span5', 'maxlength' => 255)); ?>

      <?php echo $form->textFieldRow($model, 'corporate_sme', array('class' => 'span5', 'maxlength' => 255)); ?>

      <?php echo $form->textFieldRow($model, 'product_name', array('class' => 'span5', 'maxlength' => 255)); ?>

      <?php echo $form->textFieldRow($model, 'volume_translate_min', array('class' => 'span5', 'maxlength' => 255)); ?>

      <?php echo $form->textFieldRow($model, 'volume_translate_max', array('class' => 'span5', 'maxlength' => 255)); ?>

      <?php echo $form->textFieldRow($model, 'max_commission', array('class' => 'span5', 'maxlength' => 255)); ?>

      <?php echo $form->textFieldRow($model, 'commission_increament', array('class' => 'span5', 'maxlength' => 255)); ?>

      <?php echo $form->textFieldRow($model, 'commission_banded', array('class' => 'span5', 'maxlength' => 255)); ?>

      <?php echo $form->textFieldRow($model, 'standing_charge', array('class' => 'span5', 'maxlength' => 255)); ?>

      <?php echo $form->textFieldRow($model, 'direct_dabit', array('class' => 'span5', 'maxlength' => 255)); ?>

      <?php echo $form->textFieldRow($model, 'renewal', array('class' => 'span5', 'maxlength' => 255)); ?>

      <?php echo $form->textFieldRow($model, 'renewal_obligation', array('class' => 'span5', 'maxlength' => 255)); ?>

      <?php echo $form->textFieldRow($model, 'feed_in_tarriff', array('class' => 'span5', 'maxlength' => 255)); ?>

      <?php echo $form->textFieldRow($model, 'contact_for_difference', array('class' => 'span5', 'maxlength' => 255)); ?>

      <?php echo $form->textFieldRow($model, 'capacity_machanism', array('class' => 'span5', 'maxlength' => 255)); ?>

      <?php echo $form->textFieldRow($model, 'distribution_charge', array('class' => 'span5', 'maxlength' => 255)); ?>

      <?php echo $form->textFieldRow($model, 'transmission_charge', array('class' => 'span5', 'maxlength' => 255)); ?>

      <?php echo $form->textFieldRow($model, 'balancing_charge', array('class' => 'span5', 'maxlength' => 255)); ?>

      <?php echo $form->textFieldRow($model, 'direct_dabit_mandate', array('class' => 'span5', 'maxlength' => 255)); ?>

      <?php echo $form->textFieldRow($model, 't_and_cs', array('class' => 'span5', 'maxlength' => 255)); ?>

      <?php echo $form->textFieldRow($model, 'status', array('class' => 'span5')); ?>

      <?php echo $form->textFieldRow($model, 'created', array('class' => 'span5')); ?>

      <div class="form-actions">
      <?php
      $this->widget('bootstrap.widgets.TbButton', array(
      'buttonType' => 'submit',
      'type' => 'primary',
      'label' => $model->isNewRecord ? 'Create' : 'Save',
      ));
      ?>
      </div>
      <?php */ ?>
    <?php $this->endWidget(); ?>

</div>
<div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button id="submit" class="btn btn-primary">Get Header </button>
</div>


<script>

    $(document).ready(function () {
        $("#submit").click(function (e) {
            e.preventDefault();
            if($("#Product_csvfile"))
            $("#product-form").submit();
        });

    });

    //   alert('sadfsfd');
    function getCsvHeader() {
        
        var data = $("#product-form").serialize();
        var url = '<?php echo Yii::app()->createAbsoluteUrl("/admin/product/getCsvHeader")   ?>';
        $.ajax({
            url: url,
            type: "POST",
            data: data,
            //  dataType:json,
            beforeSend: function () {

            },
            success: function (res) {
                console.log(res);
            },
        });
    }
</script>

protected/modules/admin/views/product/_partial.php
<?php
$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id' => 'users-form1',
    'enableAjaxValidation' => false,
    'action' => $this->createAbsoluteUrl("users/types"),
    'enableClientValidation' => true,
    'clientOptions' => array(
        'validateOnSubmit' => true,
    ),
    'htmlOptions' => array('enctype' => 'multipart/form-data'),
        ));
?>

<div class="control-group" id="check_boxes1">
    <?php
    
    
  //  $model->sub_type_id = explode(",", $model->sub_type_id);

//    echo $form->checkBoxListRow($model, 'sub_type_id', CHtml::listData(
//                    $model->getSubProductTypes(), 'id', 'title')
//    );
    ?>
</div>
<div class="control-group">
    <div class="form-actions">
        <?php
        $this->widget('bootstrap.widgets.TbButton', array(
            'buttonType' => 'submit',
            'type' => 'primary',
            'label' => $model->isNewRecord ? 'Save' : 'Save',
        ));
        ?>
    </div>
</div>
<?php $this->endWidget(); ?>

protected/modules/admin/views/product/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'utility',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'corporate_sme',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'product_name',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'volume_translate_min',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'volume_translate_max',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'max_commission',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'commission_increament',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'commission_banded',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'standing_charge',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'direct_dabit',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'renewal',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'renewal_obligation',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'feed_in_tarriff',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'contact_for_difference',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'capacity_machanism',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'distribution_charge',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'transmission_charge',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'balancing_charge',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'direct_dabit_mandate',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'t_and_cs',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'status',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'created',array('class'=>'span5')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/modules/admin/views/product/admin.php
<section id="manage_products">
    <div class="container-fluid">
        <div class="row">
            <div class="card">
                <div class="card-header">
                    <?php if (Yii::app()->user->hasFlash('success')): ?>
                        <div class="info">
                            <?php echo Yii::app()->user->getFlash('success'); ?>
                        </div>
                    <?php endif; ?>
                    <div class="card-title">
                        <strong>Manage Products</strong>
                    </div>

                    <?php
                    if (Yii::app()->user->isAdmin) {
                        echo CHtml::link('Create product', array('/admin/product/create'), array("class" => 'btn btn-success'));
                    }
                    ?>

                </div>
                <div class="card-body">
                    <?php
                    $this->widget('bootstrap.widgets.TbGridView', array(
                        'id' => 'product-grid',
                        'dataProvider' => $model->search(),
                        'afterAjaxUpdate' => 'function(id,options){ paginationControls(); }',
                        'filter' => $model,
                        'columns' => array(
                            'assigned_to' => array(
                                'filter' => false,//CHtml::listData(Users::getAllSuppliers(), 'id', 'fullname'),
                                'type' => 'html',
                                'name' => 'assigned_to',
                                'value' => '$data->user->username',//'CHtml::image(Yii::app()->createAbsoluteUrl("admin/users/thumbnail/file/".$data->user->image))',
                                'htmlOptions' => array('class' => 'table-images'),
                               
                                
                            ),
                            'utility' => array(
                                'name' => 'utility',
                                'filter' => false, // Product::getUtilites(),
                                'value' => 'Product::getUtilites($data->utility)',
                            ),
                            'corporate_sme' => array(
                                'name' => 'corporate_sme',
                                'filter' => false, // Product::getCorporateSME(),
                                'value' => 'Product::getCorporateSME($data->corporate_sme)',
                            ),
                            'product_name' => array(
                                'name' => 'product_name',
                                'type' => 'raw',
                                'value' => 'CHtml::link($data->product_name,array("product/view","id"=>$data->id), array("target"=>"_blank"))',
                                'filter' => false
                            ),
                            'valid_till' => array(
                                'name' => 'valid_till',
                                'type' => 'raw',
                                'value' => 'date("d-m-Y", strtotime($data->valid_till))',
                                'filter' => false
                            ),
                            'valid_from' => array(
                                'name' => 'valid_from',
                                'type' => 'raw',
                                'value' => 'date("d-m-Y", strtotime($data->valid_from))',
                                'filter' => false
                            ),
                            //
                            array(
                                'class' => 'bootstrap.widgets.TbButtonColumn',
                                'template' => '{activate}{deactivate}{calculate}',
                                'header' => 'Active',
                                'buttons' => array(
                                    'calculate' => array(
                                        'label' => '&nbsp;&nbsp;<i class="fa fa-wrench"></i>',
                                        'url' => 'Yii::app()->createAbsoluteUrl("admin/product/calculate", array("id"=>$data->id))',
                                        'options' => array('title' => 'Calculate'),
                                        'imageUrl' => false,
                                        'click' => "function(e){
                                                var url = $(this).attr('href');
                                                  $('#modal11').modal('show');
                                                e.preventDefault();
                                                $.ajax({
                                                 type: 'POST',
                                                 url: url,
                                                 success: function(res){
                                                      $('#fasdfsadf').html(res);
                                                   },
                                                });

                                                return false;
                                            }",
                                    ),
                                    'activate' => array(
                                        'label' => '&nbsp;&nbsp;<i class="fa fa-check"></i>',
                                        'visible' => '$data->status > 0', // <-- SHOW IF ROW INACTIVE
                                        'url' => 'Yii::app()->createAbsoluteUrl("admin/product/changeStatus", array("id"=>$data->id))',
                                        'options' => array('title' => 'Deactivate product'),
                                        'imageUrl' => false,
                                        'click' => "function(e){
                                                var url = $(this).attr('href');
                                                e.preventDefault();
                                                $.ajax({
                                                 type: 'POST',
                                                 url: url,
                                                 success: function(res){
                                                  $.fn.yiiGridView.update('product-grid');

                                                },
                                                });

                                                return false;
                                            }",
                                    ),
                                    'deactivate' => array(
                                        'label' => '&nbsp;&nbsp;<i class="fa fa-remove"></i>',
                                        'visible' => '$data->status == 0', // <-- SHOW IF ROW ACTIVE
                                        'url' => 'Yii::app()->createAbsoluteUrl("admin/product/changeStatus", array("id"=>$data->id))',
                                        'options' => array('title' => 'Activate product'),
                                        'imageUrl' => false,
                                        'click' => "function(e){

                                                 e.preventDefault();
                                                var url = $(this).attr('href');

                                                $.ajax({
                                                 type: 'POST',
                                                 url: url,
                                                 success: function(res){
                                                   $.fn.yiiGridView.update('product-grid');
                                                },
                                                });

                                                return false;
                                            }",
                                    ),
                                ),
                            ),
                            array(
                                'class' => 'bootstrap.widgets.TbButtonColumn',
                                'template' => '{update}{delete}{view}',
                                'header' => 'Update/Delete',
                            ),
                        ),
                    ));
                    ?>
                </div>
            </div>

        </div>
    </div>
</section>

<div class="modal fade" id="modal11" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document" id="fasdfsadf">

    </div>
</div>

protected/modules/admin/views/product/index.php
<?php
$this->breadcrumbs=array(
	'Products',
);

$this->menu=array(
	array('label'=>'Create Product','url'=>array('create')),
	array('label'=>'Manage Product','url'=>array('admin')),
);
?>

<h1>Products</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>